# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosandbox < Formula
  desc ""
  homepage "https://github.com/josephedward/gosandbox"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.1/gosandbox_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "ca4dcc3d4adec292aba69610fdb68dcf9ea19c3da5473f7f048b99fa0b0ac656"

      def install
        bin.install "gosandbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.1/gosandbox_0.1.1_Darwin_arm64.tar.gz"
      sha256 "7fa87dceed229afe3e7a83eaf28a58db20fae8302928efb34a681ccc8c7fa5e3"

      def install
        bin.install "gosandbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.1/gosandbox_0.1.1_Linux_x86_64.tar.gz"
      sha256 "9ca86ce3cae911d73b4a8b026f5b9864b1f768f0e1f4afffbeee863c9d14f858"

      def install
        bin.install "gosandbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.1/gosandbox_0.1.1_Linux_arm64.tar.gz"
      sha256 "5c70ed7c256ded8e31b171474744471bdf89fbb98b962d3c561f4984ed1200d2"

      def install
        bin.install "gosandbox"
      end
    end
  end
end
