# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosandbox < Formula
  desc ""
  homepage "https://github.com/josephedward/gosandbox"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.3/gosandbox_0.1.3_Darwin_arm64.tar.gz"
      sha256 "f7b643bcf50d2372ef6c87ed314673a7ee75c02522ca7e1ce53f1b6ef6b848e9"

      def install
        bin.install "gosandbox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.3/gosandbox_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "a52c6e784db336d704a5ce45c2d270fd180e67bf04714b1091671d0e3bdc6d05"

      def install
        bin.install "gosandbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.3/gosandbox_0.1.3_Linux_arm64.tar.gz"
      sha256 "dbbda7325c0e7d50771718b692c4e0da389b46e60743a4e9e0137308a2d5ca56"

      def install
        bin.install "gosandbox"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/josephedward/gosandbox/releases/download/v0.1.3/gosandbox_0.1.3_Linux_x86_64.tar.gz"
      sha256 "ab7991b69c932911b10a97eaf25cbac914527faf126250500a99871d79ef6164"

      def install
        bin.install "gosandbox"
      end
    end
  end
end
